### ISSUE TITLE
unable to build docker images on nitro enclave ec2 instance

### ISSUE THREAD

**Issue by d-thales** [aws/aws-nitro-enclaves-sdk-c#103]
I am able to successfully run the hello world example.  When attempting to run - 

docker build --target kmstool-instance -t kmstool-instance -f containers/Dockerfile.al2 .

get this error message and am unable to proceed.

Step 41/60 : RUN cmake3 -DCMAKE_PREFIX_PATH=/usr -DCMAKE_INSTALL_PREFIX=/usr -GNinja    -S aws-nitro-enclaves-sdk-c -B aws-nitro-enclaves-sdk-c/build
 ---> Running in 3b2d0e8191cf
CMake Error: The source directory "/tmp/crt-builder/aws-nitro-enclaves-sdk-c" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
The command '/bin/sh -c cmake3 -DCMAKE_PREFIX_PATH=/usr -DCMAKE_INSTALL_PREFIX=/usr -GNinja     -S aws-nitro-enclaves-sdk-c -B aws-nitro-enclaves-sdk-c/build' returned a non-zero code: 1

**Comment by andrewburns1** [comment]
I encountered this error when running `docker build --target kmstool-instance -t kmstool-instance -f containers/Dockerfile.al2 .

` in my home directory, however this issue does not present when running the command in the root of the repository.

**Comment by d-thales** [comment]
Are you able to be more specific as which user and at what path I should run the above command?  I am running it on the Nitro Enclave and as the default ec2-user.  I did try running on other EC2 instances and had some result and had located Dockerfile.al2 in the /home/ec2-user/ directory without adding containers directory and had same result.

**Comment by d-thales** [comment]
Thank you. I did not see these two steps in the instructions I followed.  Once I did the 2 below commands, the build was successful.  Is it possible to get these two steps more prominently called out before running the docker build?

git clone https://github.com/aws/aws-nitro-enclaves-sdk-c.git
cd aws-nitro-enclaves-sdk-c
