### ISSUE TITLE
Production Mode - Could not connect to vsock 16.3000

### ISSUE THREAD

**Issue by d-thales** [aws/aws-nitro-enclaves-sdk-c#105]
I am unable to use the kmstool in production mode, which is the equivalent of using my actual PCR0 value in lieu of the "000000" value.  When I run the production mode to start the enclave (nitro-cli run-enclave --eif-path kmstool.eif --memory 1024 --cpu-count 2), in a separate terminal, I am able to start or continue the vsock-proxy using (vsock-proxy 8000 kms.$CMK_REGION.amazonaws.com 443).  As noted because it is in production mode, this command does not work (nitro-cli console --enclave-id $ENCLAVE_ID). Result is [ E44 ] Enclave console connection failure. Such error appears when the Nitro CLI process fails to establish a connection to a running enclave's console.

IMPORTANT NOTE: I am successful performing the decrypt using debug-mode.

When I attempt to run ( docker run --network host -it kmstool-instance     /kmstool_instance --cid "$ENCLAVE_CID" --region "$CMK_REGION" "$CIPHERTEXT"), the result is always:

Could not connect to vsock 16.3000.

Is this a configuration issue on my part? Thank you.

**Comment by alcioa** [comment]
Have you updated your `"$ENCLAVE_CID"` value to the spawned production enclave CID?

**Comment by d-thales** [comment]
Brilliant! Thank you.  Here is an abbreviated sequence in Production Mode as they instructions somewhat bounce around (assumes the KMS Key Policy is updated with the actual PCR0 value and the $CIPHERTEXT is already available).

Repeating the build of enclave and running - Production Mode
Primary Terminal:
nitro-cli build-enclave --docker-uri kmstool-enclave --output-file kmstool.eif
nitro-cli run-enclave --eif-path kmstool.eif --memory 1024 --cpu-count 2

New Terminal:
CMK_REGION=ca-central-1 # The region where you created your AWS KMS CMK
vsock-proxy 8000 kms.$CMK_REGION.amazonaws.com 443

Back to Primary (first) terminal
CMK_REGION=ca-central-1 # The region where you created your AWS KMS CMK
ENCLAVE_CID=$(nitro-cli describe-enclaves | jq -r .[0].EnclaveCID)
docker run --network host -it kmstool-instance \
    /kmstool_instance --cid "$ENCLAVE_CID" --region "$CMK_REGION" "$CIPHERTEXT"
nitro-cli terminate-enclave --enclave-name kmstool # use to terminate enclave
