### ISSUE TITLE
Got non-200 answer from KMS: 400 / Could not decrypt ciphertext

### ISSUE THREAD

**Issue by chargarlic** [aws/aws-nitro-enclaves-sdk-c#126]
I get the following error when i try to perform a decrypt operation with the kmstool_enclave_cli inside the enclave. Permissions are set per documentation and I am able to decrypt from the EC2 Instance/ use KMS correctly.
testing this out in --debug-mode and using a fairly lenient KMS policy. Instance credentials are used from within the enclave...
Compiled using v0.4.1

```INFO] [2023-09-19T03:19:44Z] [00007f1feac22840] [event-loop] - id=0x235f650: Initializing edge-triggered epoll
[INFO] [2023-09-19T03:19:44Z] [00007f1feac22840] [event-loop] - id=0x235f650: Using eventfd for cross-thread notifications.
[INFO] [2023-09-19T03:19:44Z] [00007f1feac22840] [event-loop] - id=0x235f650: Starting event-loop thread.
[INFO] [2023-09-19T03:19:44Z] [00007f1feac22840] [dns] - id=0x242afb0: Initializing default host resolver with 8 max host entries.
[INFO] [2023-09-19T03:19:44Z] [00007f1feac22840] [channel-bootstrap] - id=0x242b390: Initializing client bootstrap with event-loop group 0x2355fb0
[INFO] [2023-09-19T03:19:44Z] [00007f1fea420700] [event-loop] - id=0x235f650: main loop started
[INFO] [2023-09-19T03:19:44Z] [00007f1fea420700] [event-loop] - id=0x235f650: default timeout 100000, and max events to process per tick 100
[INFO] [2023-09-19T03:19:44Z] [00007f1fea420700] [socket] - id=0x242d750 fd=6: connection success
[INFO] [2023-09-19T03:19:44Z] [00007f1fea420700] [http-connection] - id=0x7f1fdc015d60: HTTP/1.1 client connection established.
Connected.
[INFO] [2023-09-19T03:19:44Z] [00007f1feac22840] [AuthSigning] - (id=0x23fded0) Signing successfully built canonical request for algorithm SigV4, with contents
POST
/

content-length:xxx
content-type:application/x-amz-json-1.1
host:kms.us-west-2.amazonaws.com
x-amz-content-sha256:xxxx
x-amz-date:xxxx
x-amz-security-token:xxxx
x-amz-target:TrentService.Decrypt

content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-security-token;x-amz-target
xxxx

[INFO] [2023-09-19T03:19:44Z] [00007f1feac22840] [AuthSigning] - (id=0x23fded0) Signing successfully built string-to-sign via algorithm SigV4, with contents
AWS4-HMAC-SHA256
20230919T031944Z
20230919/us-west-2/kms/aws4_request
xxxx

[INFO] [2023-09-19T03:19:44Z] [00007f1feac22840] [AuthSigning] - (id=0x23fded0) Http request successfully built final authorization value via algorithm SigV4, with contents
AWS4-HMAC-SHA256 Credential=xxx/xxx/us-west-2/kms/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-security-token;x-amz-target, Signature=xxxx

Got non-200 answer from KMS: 400
Could not decrypt ciphertext
Could not decrypt
```

**Comment by richardfan1126** [comment]
@chargarlic Could you check the CloudTrail log to see if there is any error message from the KMS request?

Ref: https://docs.aws.amazon.com/kms/latest/developerguide/logging-using-cloudtrail.html#searching-kms-ct

**Comment by chargarlic** [comment]
> @chargarlic Could you check the CloudTrail log to see if there is any error message from the KMS request?
> 
> Ref: https://docs.aws.amazon.com/kms/latest/developerguide/logging-using-cloudtrail.html#searching-kms-ct

Hi @richardfan1126 I did but there were no errors for Decrypt. (Also had a session with KMS support where we tried to trigger any errors but it never came up). They suggested reaching out to the nitro SDK team/ raise an issue here for further troubleshooting

**Comment by chargarlic** [comment]
> @chargarlic Could you check the CloudTrail log to see if there is any error message from the KMS request?
> 
> Ref: https://docs.aws.amazon.com/kms/latest/developerguide/logging-using-cloudtrail.html#searching-kms-ct

are there any other alternatives to the aws-nitro-enclaves-sdk-c that could do the Decrypt operation ?

**Comment by petreeftime** [comment]
I suggest adding additional logging to: https://github.com/aws/aws-nitro-enclaves-sdk-c/blob/main/source/kms.c#L2666-L2670 to see the exact error message. 
```c
 fprintf(stderr, "Got non-200 answer from KMS: %d - %s\n", rc, aws_string_c_str(response));
```

Do the events from the enclave show up in CloudTrail?

**Comment by chargarlic** [comment]
> ```c
> ```c
>  fprintf(stderr, "Got non-200 answer from KMS: %d - %s\n", rc, aws_string_c_str(response));
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

Thanks for that, this is what i see with the debug message
```Got non-200 answer from KMS: 400 - {"__type":"InvalidSignatureException","message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}```

**Comment by petreeftime** [comment]
How are you passing the credentials to the enclave? Are you also passing the Session Token?

**Comment by chargarlic** [comment]
> How are you passing the credentials to the enclave? Are you also passing the Session Token?

```TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` \
&& curl -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/iam/security-credentials/<instance-iam-role> > assumed-role.json
cat assumed-role.json | socat - VSOCK-CONNECT:$ENCLAVE_CID:7777```

On the instance side i have socat running listening for the creds file and then load it into env vars (This is a blocking action at start of enclave)

**Comment by petreeftime** [comment]
Is it possible that the env vars might have some additional characters, perhaps `"`, `\n` or ` `, or the file is for some reason not copied correctly? Would it be possible to print back the environment variables from the program and check?

**Comment by chargarlic** [comment]
> Is it possible that the env vars might have some additional characters, perhaps `"`, `\n` or ` `, or the file is for some reason not copied correctly? Would it be possible to print back the environment variables from the program and check?

I do something along lines of `export AWS_ACCESS_KEY_ID=$(jq -r '.AccessKeyId' creds)` , I am able to use the same creds to do list-keys/ generate-random and even encrypt with the aws-cli .  I did try to print back env vars and don't see anything that standsout

**Comment by chargarlic** [comment]
This has been resolved by itself. Closing this out
