### ISSUE TITLE
CMakeLists appears to be incomplete

### ISSUE THREAD

**Issue by aidansteele** [aws/aws-nitro-enclaves-sdk-c#19]
Hi,

When I run cmake I get the following errors - it seems that a handful of things are missing. Is this intentional, or should I be able to build the project outside of AWS?

```
CMake Error at CMakeLists.txt:32 (include):
  include could not find load file:

    AwsCFlags


CMake Error at CMakeLists.txt:33 (include):
  include could not find load file:

    AwsCheckHeaders


CMake Error at CMakeLists.txt:34 (include):
  include could not find load file:

    AwsSharedLibSetup


CMake Error at CMakeLists.txt:35 (include):
  include could not find load file:

    AwsSanitizers


CMake Error at CMakeLists.txt:36 (include):
  include could not find load file:

    AwsFindPackage


CMake Error at CMakeLists.txt:56 (aws_set_common_properties):
  Unknown CMake command "aws_set_common_properties".
```

**Comment by petreeftime** [comment]
The build process is definitely not well documented, sorry for that. I think you might be missing the required dependencies, especially aws-c-common. You can find the required dependencies [here](https://github.com/aws/aws-nitro-enclaves-sdk-c#dependencies), and also we have a build container that contains all the dependencies and their build instructions, even if it's not direct documentation: [Dockerfile.al2](https://github.com/aws/aws-nitro-enclaves-sdk-c/blob/main/containers/Dockerfile.al2).
