### ISSUE TITLE
Support for encrypt

### ISSUE THREAD

**Issue by tomtau** [aws/aws-nitro-enclaves-sdk-c#24]
Currently, only decrypt, generate_data_key and generate_random are supported: https://github.com/aws/aws-nitro-enclaves-sdk-c/blob/main/include/aws/nitro_enclaves/kms.h#L710

**Comment by msharmavikram** [comment]
@tomtau we too need support for encryption inside the enclave and it is sad that the nitro-enclave native support has only decrypt functionality.  

Also thanks for creating the PR on adding support for encrypting. We will test it out and update the thread.
