### ISSUE TITLE
Decrypting file inside enclave application - kmstool-enclave-cli rewrite

### ISSUE THREAD

**Issue by giulianopietoso-apheris** [aws/aws-nitro-enclaves-sdk-c#31]
I have been using the [kmstool-enclave-cli](https://github.com/aws/aws-nitro-enclaves-sdk-c/tree/main/bin/kmstool-enclave-cli) to decrypt some data using KMS from inside my enclave application.

Since the ciphertext is a cli parameter, I wonder if the tool currently supports decrypting files? If so, how could this be achieved? If not, is it on the roadmap?

Thanks!

**Comment by richardfan1126** [comment]
@giulianopietoso-apheris The tool is built on top of KMS API, so it only accepts the base64-encoded ciphertext.

To decrypt a file, you'll need to read the file content, encode it in Base64, and pass it to the tool as a parameter.

**Comment by giulianopietoso-apheris** [comment]
Thank you for the answer. Are there any known limitations on file size? The ciphertext parameter could get pretty huge.

**Comment by petreeftime** [comment]
KMS API supports blobs to 6144 (base64) bytes. For anything more than that, envelope encryption must be used.
https://docs.aws.amazon.com/kms/latest/APIReference/API_Decrypt.html#API_Decrypt_RequestSyntax

**Comment by petreeftime** [comment]
It's possible to use envelope encryption for files larger than a few kilobytes, by encrypting a data key or using the GenerateDataKey API.

**Comment by giulianopietoso-apheris** [comment]
Thank you everyone for the help.
