### ISSUE TITLE
kmstool untrusted certificate error

### ISSUE THREAD

**Issue by dsandip07** [aws/aws-nitro-enclaves-sdk-c#32]
kmstool-enclave console prints error message which indicates TLS negotiation error.  As a result of this, not able to use KMS tool at all. Followed steps exactly as written in the KMSTool README.  Please see a console output snippet. 

[WARN] [2021-01-21T15:16:05Z] [00007fcfd91f1880] [socket] - id=0xb9d440 fd=10: setsockopt() for NO_SIGNAL failed with errno 92. If you are having SIGPIPE signals thrown, you may want to install a signal trap in your application layer.
[INFO] [2021-01-21T15:16:05Z] [00007fcfd7617700] [socket] - id=0xb9d440 fd=10: connection success
[WARN] [2021-01-21T15:16:05Z] [00007fcfd7617700] [tls-handler] - id=0x7fcfc8011c80: **negotiation failed with error Certificate is untrusted** (Error encountered in /tmp/crt-builder/s2n/tls/s2n_x509_validator.c line 355)
[ERROR] [2021-01-21T15:16:05Z] [00007fcfd7617700] [http-connection] - static: Client connection failed with error 1029 (AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE).
Connection failed with error aws-c-io: AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE, TLS (SSL) negotiation failed
Could not create new client
[INFO] [2021-01-21T15:16:05Z] [00007fcfd6615700] [event-loop] - id=0xb8dcc0: Destroying event_loop
[INFO] [2021-01-21T15:16:05Z] [00007fcfd6615700] [event-loop] - id=0xb8dcc0: Stopping event-loop thread.
[INFO] [2021-01-21T15:16:05Z] [00007fcfd6615700] [event-loop] - id=0xab5e50: Destroying event_loop
[INFO] [2021-01-21T15:16:05Z] [00007fcfd6615700] [event-loop] - id=0xab5e50: Stopping event-loop thread.
Sesssion ended

Please look into the issue and suggest a resolution via README update or other places.

**Comment by petreeftime** [comment]
Hi. This usually occurs when the `vsock-proxy` endpoint does not match the region set in `kmstool`. You can set the `kmstool` region via the `kmstool-instance` `--region` parameter at runtime or via `kmstool-enclave` `--region` parameter when building the enclave. If neither is specified, the default is to use `us-east-1`.

**Comment by petreeftime** [comment]
It does seem this parameter isn't documented, since it was added later.

**Comment by petreeftime** [comment]
This was clarified in #36.
