### ISSUE TITLE
Question: How does the plaintext after KMS decryption get back into the enclave?

### ISSUE THREAD

**Issue by blmalone** [aws/aws-nitro-enclaves-sdk-c#51]
I've been able to provision an EC2 instance with the Nitro Enclave [sample](https://github.com/aws/aws-nitro-enclaves-sdk-c/blob/main/docs/kmstool.md) running successfully. 

After spending some time reading through the code, I'd like to piece together _how KMS knows to decrypt the ciphertext and return the plaintext_.

The sample application has two parts, `kmstool-enclave` and `kmstool-instance`.

Of course, after encrypting data `X` to key `Y` (stored in KMS), we will want to decrypt X with Y only by the enclave. I'm aware that this is enforced by the KMS CMK policy (by providing the value of PCR0).

What isn't clear to me is that when I run the following:

```
# Run docker with network host to allow it to fetch IAM credentials with IMDSv2
docker run --network host -it kmstool-instance \
    /kmstool_instance --cid "$ENCLAVE_CID" --region "$CMK_REGION" "$CIPHERTEXT"
```

for decryption, how does the enclave actually:
1. Establish a secure channel with KMS
2. Securely retrieve the plaintext from KMS, I'm basing this on the assumption that all cryptographic operations happen within CloudHSM and decryption is not occurring in the enclave itself.

(My guess is that there is some attestation happening beforehand that is abstracted away? Allowing for a session to be established between enclave and KMS.)

**Extra Notes:** 

From attestation documentation:

> The Nitro Enclaves SDK includes some APIs (kms-decrypt, kms-generate-data-key, and kms-generate-random) that integrate with AWS KMS. When these APIs are called against a specific key, the enclave's attestation document, which includes its measurements, is attached to the request. AWS KMS receives the request and validates the measurements in the provided attestation document against the measurements specified in the condition keys of the CMK policy. It uses this information to determine whether the enclave should be granted permission to perform the requested action using the requested CMK.

Thanks in advance.

**Comment by blmalone** [comment]
@petreeftime Tagging you as you seem to be actively replying to recent issues.

**Comment by richardfan1126** [comment]
@blmalone 

The API call between the enclave and KMS is using HTTPS, so the data in transit is encrypted and secured.

In addition, when `kmstool-enclave` generates the attestation document, it attaches its public key (**enclave public key**) to it. The workflow is as follow (Ref: https://docs.aws.amazon.com/enclaves/latest/user/flow.html#attest-decrypt):

1. Decrypt the original ciphertext (**ciphertext 1**) using its key (**KMS key**)
2. Encrypt the plaintext using **enclave public key** (Let's call the encrypted data as **ciphertext 2**)
3. Send the **ciphertext 2** back to the enclave
4. `kmstool-enclave` uses its private key to decrypt **ciphertext 2** and get the plaintext

As long as the enclave private key doesn't go out of the enclave, even an attacker cracks the HTTPS encryption and get the KMS response, he / she still cannot get the original plaintext.

If you take a look at the code, you will find it generating RSA keypair, putting the public key to the attestation document, and decrypting KMS response using the keypair:

- https://github.com/aws/aws-nitro-enclaves-sdk-c/blob/46a564270e5713559116833fe1303eab4c4bad0d/source/kms.c#L2503
- https://github.com/aws/aws-nitro-enclaves-sdk-c/blob/46a564270e5713559116833fe1303eab4c4bad0d/source/kms.c#L2628
- https://github.com/aws/aws-nitro-enclaves-sdk-c/blob/46a564270e5713559116833fe1303eab4c4bad0d/source/kms.c#L2652

I've created a sample project using Python to demonstrate the entire process, you can take a look and it may help you understand:
https://github.com/richardfan1126/nitro-enclave-python-demo/tree/master/attestation_verifier

**Comment by blmalone** [comment]
@richardfan1126 Thank you, great explanation.
