### ISSUE TITLE
How to request attestation document (+set user_data field)

### ISSUE THREAD

**Issue by Jonas-Metzger** [aws/aws-nitro-enclaves-sdk-c#57]
What function do I call to request the attestation document, and how do I set the user_data field? Can't find a pointer to the right command anywhere in the docs. Thanks!

**Comment by petreeftime** [comment]
The attestation API is part of the https://github.com/aws/aws-nitro-enclaves-nsm-api/ repository and I see you opened a similar question there as well: https://github.com/aws/aws-nitro-enclaves-nsm-api/issues/9.

I will answer the question there.
