### ISSUE TITLE
InvalidCiphertextException

### ISSUE THREAD

**Issue by Allen-yan** [aws/aws-nitro-enclaves-sdk-c#68]
When I use kmstool_enclave_cli to decrypt a base64 cipher text, it always return 

> Response: {"__type":"InvalidCiphertextException"}
Got non-200 answer from KMS: 400

Here's my python code outside enclave, it works well for the same cipher text:

`kms_client.decrypt(
            KeyId=key_id,
            CiphertextBlob=base64.b64decode(cipher_),
            EncryptionAlgorithm='RSAES_OAEP_SHA_256'
        )
`
Because the kmstool_enclave_cli using the  Base64-encoded ciphertext , so I do not decode the ciphertext to base64 before pass to the kmstool_enclave_cli. 
This the only different between the python decrypt and the kmstool_enclave_cli .

Here's the logging when invoke kmstool_enclave_cli decrypt method:
`
[INFO] [2021-11-11T14:43:06Z] [00007f35a178e880] [event-loop] - id=0x222f130: Initializing edge-triggered epoll
[INFO] [2021-11-11T14:43:06Z] [00007f35a178e880] [event-loop] - id=0x222f130: Using eventfd for cross-thread notifications.
[INFO] [2021-11-11T14:43:06Z] [00007f35a178e880] [event-loop] - id=0x222f130: Starting event-loop thread.
[INFO] [2021-11-11T14:43:06Z] [00007f35a178e880] [dns] - id=0x230f540: Initializing default host resolver with 8 max host entries.
[INFO] [2021-11-11T14:43:06Z] [00007f35a178e880] [channel-bootstrap] - id=0x2301890: Initializing client bootstrap with event-loop group 0x22712d0
[INFO] [2021-11-11T14:43:06Z] [00007f35a0f8c700] [event-loop] - id=0x222f130: main loop started
[INFO] [2021-11-11T14:43:06Z] [00007f35a0f8c700] [event-loop] - id=0x222f130: default timeout 100000, and max events to process per tick 100
[INFO] [2021-11-11T14:43:06Z] [00007f35a0f8c700] [socket] - id=0x23103d0 fd=6: connection success
Connected.
[INFO] [2021-11-11T14:43:06Z] [00007f35a0f8c700] [http-connection] - id=0x7f3594015dd0: HTTP/1.1 client connection established.
[INFO] [2021-11-11T14:43:06Z] [00007f35a178e880] [AuthSigning] - (id=0x22df7b0) Signing successfully built canonical request for algorithm SigV4, with contents
POST
/

content-length:6827
content-type:application/x-amz-json-1.1
host:kms.ap-northeast-2.amazonaws.com
x-amz-content-sha256:xxxx
x-amz-date:20211111T144306Z
x-amz-target:TrentService.Decrypt

content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-target
xxxx

[INFO] [2021-11-11T14:43:06Z] [00007f35a178e880] [AuthSigning] - (id=0x22df7b0) Signing successfully built string-to-sign via algorithm SigV4, with contents
AWS4-HMAC-SHA256
20211111T144306Z
20211111/ap-northeast-2/kms/aws4_request
xxx

[INFO] [2021-11-11T14:43:06Z] [00007f35a178e880] [AuthSigning] - (id=0x22df7b0) Http request successfully built final authorization value via algorithm SigV4, with contents
AWS4-HMAC-SHA256 Credential=<access-id>/20211111/ap-northeast-2/kms/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-target, Signature=xxx

Response: {"__type":"InvalidCiphertextException"}
Got non-200 answer from KMS: 400
`
I have stuck at this trouble for many days. NEED HELP!

**Comment by alcioa** [comment]
@Allen-yan is this still relevant?
