### ISSUE TITLE
Replay attack protection in KMS cryptographic attestation example

### ISSUE THREAD

**Issue by ThorodanBrom** [aws/aws-nitro-enclaves-sdk-c#74]
Hello,

Is there any reason that no nonce or `user_data` as mentioned in the [Verifying the root of trust](https://docs.aws.amazon.com/enclaves/latest/user/verify-root.html) in the KMS attestation example. Does the interaction between KMS and enclave provide any in-built protection for replay attacks (i.e. sending the same attestation document multiple times)?

**Comment by petreeftime** [comment]
Indeed, the replay protection in this case is provided by using a TLS connection for communicating with KMS, which provides both replay protection and authentication of the KMS endpoint. KMS does re-encrypt the retrieved data to a private key generated by the enclave, such that only the enclave can use the decrypted data.

**Comment by ThorodanBrom** [comment]
@petreeftime many thanks for the answer!
