### ISSUE TITLE
Undocummented endpoint configuration

### ISSUE THREAD

**Issue by voronaam** [aws/aws-nitro-enclaves-sdk-c#75]
There was a new version 15 days ago which added an option to configure the endpoint used by the kms tool.

But the documentation has not been updated to reflect that.

Following the documentation in `docs/kmstool.md` results in the following error:

```
[ERROR] [2022-05-04T19:44:38Z] [00007f961e1fd700] [http-connection] - id=0x7f9610014a80: Cannot create request stream, error 2054 (AWS_ERROR_HTTP_INVALID_PATH)

```

**Comment by petreeftime** [comment]
I will look into adding documentation, but the previous setup should still work as it was described.

**Comment by voronaam** [comment]
Thank you. This clarifies the confusion. Sorry I did not close the issue earlier.
