### ISSUE TITLE
SSL cerificate to talk to KMS

### ISSUE THREAD

**Issue by voronaam** [aws/aws-nitro-enclaves-sdk-c#80]
I am trying to use this SDK and am getting the following error:
```
Connection failed with error aws-c-io: AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE, TLS (SSL) negotiation failed
```

I suspect that my EIF image is missing a root certificate required to establish a TLS connection to AWS. I am not using `amazonlinux` as the base image for my Docker container (which is later used to build an EIF).

Is there a documentation on which certificates I should copy over from `amazonlinux` into my Docker image for the TLS to work?

Are there environment variable I could set to enable more verbose logging?

**Comment by petreeftime** [comment]
For logging, the only way is to initialize the logging library with a more verbose mode, as shown here: https://github.com/aws/aws-nitro-enclaves-sdk-c/blob/main/bin/kmstool-enclave/main.c#L404-L411, https://github.com/aws/aws-nitro-enclaves-sdk-c/blob/main/bin/kmstool-instance/main.c#L463-L471. [AWS_LL_TRACE](https://github.com/awslabs/aws-c-common/blob/main/include/aws/common/logging.h#L13-L19) is the most verbose.

For certificates, amazonlinux stores them under `/etc/pki/tls/certs/ca-bundle.crt` and `/etc/pki/tls/certs/ca-bundle.trust.crt`, but they should be available to install under most common distros. aws-c-io will look for the certs at the locations mentioned here: https://github.com/awslabs/aws-c-io/blob/cfe553a770e9c2d1c93b8cdfb870b9f2a46b436e/source/s2n/s2n_tls_channel_handler.c#L101-L169.

**Comment by voronaam** [comment]
Thank you. Looks like I copied the certificates in the right place. But that did not help. I will attempt to enable more verbose logging. This is a bit more complicated, since I am using this SDK from Rust and anything I call requires a bit of care around Rust/C FFI.

I am closing this issue, since you have answered all the questions I had so far. Thank you!
