### ISSUE TITLE
AWS Nitro enclave shutting down automatically

### ISSUE THREAD

**Issue by vahaj** [aws/aws-nitro-enclaves-sdk-c#89]
We have created a nitro-based ec2 instance by using instance type c6a.8xlarge and have created a NodeJS-based application.

The following operations are performed inside the ec2 instance.

Enclave was generated by using the following command and the .eif file was successfully created

**Command =** nitro-cli build-enclave --docker-uri ec2-user/nitro-test-app:latest --output-file nitro-enclave.eif

Enclave was run by using the following command.

**Command =** nitro-cli run-enclave --cpu-count 2 --memory 3524 --eif-path nitro-test.eif --debug-mode

The results of the run command were as follows

Start allocating memory... Started enclave with enclave-cid: 16, memory: 3524 MiB, cpu-ids: [1, 17]

{ 
  "EnclaveName": "hello", 
  "EnclaveID": "i-096e001cdd5c912c9-enc182d5585cfe18db",
  "ProcessID": 7666,
  "EnclaveCID": 16,
  "NumberOfCPUs": 2,
  "CPUIDs": [ 1, 17 ],
  "MemoryMiB": 3524
}

But when we run the command to check the results of the started enclave the results were empty

**Command =** nitro-cli describe-enclaves 
**Result =** []

Below are the results of the logs

**Logs:**

[enc-*******0f0dc91:***0][WARN][2022-08-24T22:35:28.916Z][src/enclave_proc/mod.rs:207] Received hang-up event from the enclave. The enclave process will shut down.

[enc-*******0f0dc91:***0][INFO][2022-08-24T22:35:28.916Z][src/enclave_proc/mod.rs:541] Enclave process 5430 exited event loop.

What could be the possible reason that the enclave instance is immediately stopping after instantiating?

**Comment by richardfan1126** [comment]
Can you try running your image on docker first and see if it exits immediately?

**Comment by vahaj** [comment]
thanks @richardfan1126 for your response, yes I have tried this as well and it was still exiting immediately.

**Comment by richardfan1126** [comment]
Then you should fix your `Dockerfile`

Have you set the `RUN` or `ENTRYPOINT`?

**Comment by vahaj** [comment]
@richardfan1126 docker image is up and running on the linux ec2 instance below are the results

CONTAINER ID   IMAGE     COMMAND                  CREATED         STATUS         PORTS      NAMES
4b4cf988801b   cisca     "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes   8080/tcp   boring_moser

I ran this command  = nitro-cli run-enclave --enclave-name nitro_enclave --cpu-count 2 --memory 3516 --eif-path hello.eif --enclave-cid 10

Result = Start allocating memory...
Started enclave with enclave-cid: 10, memory: 3516 MiB, cpu-ids: [1, 17]
{
  "EnclaveName": "nitro_enclave",
  "EnclaveID": "i-0723118e06c5d205c-enc182df10d5942db3",
  "ProcessID": 6116,
  "EnclaveCID": 10,
  "NumberOfCPUs": 2,
  "CPUIDs": [
    1,
    17
  ],
  "MemoryMiB": 3516
}

But when I ran **nitro-cli describe-enclaves**
**Result are empty** = []

**Log results =** 

[enc-xxxxxxx:6116][INFO][2022-08-27T11:29:58.666Z][src/enclave_proc/mod.rs:571] Enclave process PID: 6116
[enc-xxxxxxx:6116][INFO][2022-08-27T11:29:58.666Z][src/enclave_proc/mod.rs:479] Received command: Run
[enc-xxxxxxx:6116][INFO][2022-08-27T11:29:58.666Z][src/enclave_proc/mod.rs:272] Run args = RunEnclavesArgs { eif_path: "hello.eif", enclave_cid: Some(10), memory_mib: 3516, cpu_ids: None, debug_mode: None, attach_console: false, cpu_count: Some(2), enclave_name: Some("nitro_enclave") }
[enc-xxxxxxx:6116][INFO][2022-08-27T11:29:58.667Z][src/enclave_proc/resource_manager.rs:371] Allocating memory regions to hold 3686793216 bytes.
[enc-xxxxxxx:6116][INFO][2022-08-27T11:29:58.667Z][src/enclave_proc/resource_manager.rs:453] Allocated 225 region(s): 222 page(s) of 2 MB, 3 page(s) of 1024 MB
[enc-xxxxxxx:6116][INFO][2022-08-27T11:29:59.039Z][src/enclave_proc/resource_manager.rs:693] Finished initializing memory.
[enc-xxxxxxx:6116][INFO][2022-08-27T11:30:08.382Z][src/enclave_proc/mod.rs:281] Enclave ID = i-0723118e06c5d205c-enc182df10d5942db3
[enc-182df10d5942db3:6116][WARN][2022-08-27T11:30:08.555Z][src/enclave_proc/mod.rs:207] Received hang-up event from the enclave. Enclave process will shut down.
[enc-182df10d5942db3:6116][INFO][2022-08-27T11:30:08.555Z][src/enclave_proc/mod.rs:541] Enclave process 6116 exited event loop.

CMD is set in Docker file, following is my docker file

FROM node:16

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE 8080
CMD [ "node", "server.js" ]

**Comment by richardfan1126** [comment]
Can you run `nitro-cli console` and see the application log?

I doubt that your image can even start because the Nitro Enclaves doesn't have network connection and you cannot expose a port on it

**Comment by vahaj** [comment]
@richardfan1126 thanks for asking it again, yeah it was fixed. Problem was in my Docker file.
